version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
    environment:
      ENDPOINT: ${ENDPOINT}
    
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    environment:
      APPID: ${APPID}
      MAP_ENDPOINT: ${MAP_ENDPOINT}
      TARGET_CITY: ${TARGET_CITY}
    volumes:
      - ./backend:/app